#!/bin/bash

usage() { echo -e "Formato:\n$0 <acción> <salidas>\nAcciones: [-1: encender | -0: apagar]\nSalidas: [-a: Todas | -n: Salida x | -f: Desde la salida x | -l: Hasta la salida y]" 1>&2; exit 1; }

x=""
f=""
l=""

while getopts ":01f:l:" o; do
	case "${o}" in
		1)
			x=1
			;;
		0)
			x=0
			;;
		f)
			f=${OPTARG}
			;;
		l)
			l=${OPTARG}
			;;
		:)
			echo "Invalid option: $OPTARG requires an argument" 1>&2
			;;
		\?)
			usage
			;;
	esac
done
shift $((OPTIND-1))

if [ ${x} -eq 1 ]; then while [ ${f} -le ${l} ]; do { printf "practica\ncos\n1\n${f}\n1\nyes\n\n\033\0334\n"; } | telnet pdu-acomp.disca.upv.es; f=$(( ${f} + 1)); done else while [ ${f} -le ${l} ]; do { printf "practica\ncos\n1\n${f}\n2\nyes\n\n\033\0334\n"; } | telnet pdu-acomp.disca.upv.es; f=$(( ${f} + 1)); done
fi
	
echo "End of the script. Use $0 -h to ask for help";

exit 1
;;			
			
